<main class="grid min-h-screen lg:grid-cols-2">
    <section class="relative hidden overflow-hidden bg-primary px-12 py-14 text-white lg:flex lg:flex-col lg:justify-between">
        <div class="absolute -right-24 -top-20 h-96 w-96 rounded-full bg-blue-400/20"></div><div class="absolute -bottom-40 -left-20 h-96 w-96 rounded-full border-[50px] border-blue-300/10"></div>
        <div class="relative flex items-center gap-4"><div class="flex h-16 w-16 items-center justify-center rounded-2xl bg-white p-2 shadow-xl"><img src="<?= e(asset('images/logo.webp')) ?>" alt="Logo Perumda Tirtanadi" class="h-full w-full object-contain"></div><div><p class="text-lg font-bold tracking-wide">PERUMDA TIRTANADI</p><p class="text-sm text-blue-200">Cabang Medan Denai</p></div></div>
        <div class="relative max-w-xl"><p class="mb-4 text-sm font-semibold uppercase tracking-[.25em] text-blue-300">Sistem Informasi Pelanggan</p><h1 class="text-4xl font-bold leading-tight">Status pemutusan dan daftar ulang, dalam satu tempat.</h1><p class="mt-6 max-w-md text-base leading-7 text-blue-100">Kelola data pelanggan nonaktif secara aman, terukur, dan mudah dipahami oleh seluruh petugas kantor.</p><div class="mt-10 flex gap-3 text-sm text-blue-100"><span class="rounded-full bg-white/10 px-4 py-2">Data terintegrasi</span><span class="rounded-full bg-white/10 px-4 py-2">Akses berbasis peran</span></div></div>
        <p class="relative text-xs text-blue-300">© <?= date('Y') ?> Perumda Tirtanadi</p>
    </section>
    <section class="flex items-center justify-center px-5 py-10 sm:px-10"><div class="w-full max-w-md">
        <div class="mb-10 lg:hidden"><div class="flex items-center gap-3"><div class="h-12 w-12 rounded-xl bg-primary p-1.5"><img src="<?= e(asset('images/logo.webp')) ?>" alt="Logo Tirtanadi" class="h-full w-full object-contain"></div><div><p class="font-bold text-primary">PERUMDA TIRTANADI</p><p class="text-xs text-slate-500">Cabang Medan Denai</p></div></div></div>
        <p class="text-sm font-semibold uppercase tracking-wider text-primary">Selamat datang</p><h2 class="mt-2 text-3xl font-bold text-slate-900">Masuk ke sistem</h2><p class="mt-2 text-sm leading-6 text-slate-500">Gunakan akun yang telah diberikan administrator.</p>
        <form method="post" action="<?= e(url('/login')) ?>" class="mt-8 space-y-5" novalidate><?= csrf_field() ?>
            <div><label for="username" class="mb-2 block text-sm font-semibold text-slate-700">Username</label><input id="username" name="username" value="<?= e(old('username')) ?>" required autofocus autocomplete="username" class="form-input <?= error('username') ? 'form-input-error' : '' ?>" placeholder="Masukkan username"><p class="form-error"><?= e(error('username') ?? '') ?></p></div>
            <div><label for="password" class="mb-2 block text-sm font-semibold text-slate-700">Password</label><div class="relative"><input id="password" type="password" name="password" required autocomplete="current-password" class="form-input pr-12 <?= error('password') ? 'form-input-error' : '' ?>" placeholder="Masukkan password"><button type="button" class="password-toggle absolute inset-y-0 right-0 px-4 text-sm font-semibold text-primary" aria-label="Tampilkan password">Lihat</button></div><p class="form-error"><?= e(error('password') ?? '') ?></p></div>
            <button class="flex w-full items-center justify-center rounded-xl bg-primary px-5 py-3.5 text-sm font-bold text-white shadow-lg shadow-blue-900/20 transition hover:bg-primary-dark focus:outline-none focus:ring-4 focus:ring-blue-200">Masuk ke Sistem <span class="ml-2">→</span></button>
        </form>
        <div class="mt-8 rounded-xl border border-blue-100 bg-blue-50 p-4 text-xs leading-5 text-slate-600"><p class="font-bold text-primary">Akun demo</p><p class="mt-1">Admin: <b>admin</b> / Admin123! &nbsp;·&nbsp; Pimpinan: <b>pimpinan</b> / Pimpinan123!</p></div>
    </div></section>
</main>
