<main class="auth-page grid min-h-screen lg:grid-cols-2">
    <section class="auth-panel relative hidden overflow-hidden px-12 py-14 lg:flex lg:flex-col lg:justify-between">
        <div class="absolute inset-x-0 bottom-0 h-32 opacity-20" aria-hidden="true"><svg viewBox="0 0 1440 160" class="h-full w-full fill-none stroke-current" preserveAspectRatio="none"><path d="M0 98c206-65 360 45 600 4 238-41 415-91 840-22" stroke-width="2"/><path d="M0 126c210-64 431 37 674-2 230-37 420-62 766-15" stroke-width="1.5"/></svg></div>
        <div class="relative flex items-center gap-4"><div class="flex h-16 w-16 items-center justify-center rounded-xl bg-white p-2 shadow-lg"><img src="<?= e(asset('images/logo.webp')) ?>" alt="Logo Perumda Tirtanadi" class="h-full w-full object-contain"></div><div><p class="text-lg font-bold tracking-wide">PERUMDA TIRTANADI</p><p class="auth-meta text-sm">Cabang Medan Denai</p></div></div>
        <div class="relative max-w-xl"><p class="auth-kicker mb-4 text-sm font-semibold uppercase tracking-[.2em]">Sistem Informasi Pelanggan</p><h1 class="text-4xl font-bold leading-tight">Data pelanggan dan layanan lapangan dalam satu sistem.</h1><p class="auth-copy mt-6 max-w-md text-base leading-7">Kelola pelanggan, tagihan, pemutusan, dan daftar ulang dengan alur kerja yang jelas untuk petugas cabang.</p><div class="auth-meta mt-10 flex gap-5 text-sm"><span>Data terintegrasi</span><span aria-hidden="true">•</span><span>Akses berbasis peran</span></div></div>
        <p class="auth-meta relative text-xs">© <?= date('Y') ?> Perumda Tirtanadi</p>
    </section>
    <section class="auth-form-panel flex items-center justify-center px-5 py-10 sm:px-10"><div class="w-full max-w-md">
        <div class="mb-10 lg:hidden"><div class="flex items-center gap-3"><div class="h-12 w-12 rounded-xl bg-primary p-1.5"><img src="<?= e(asset('images/logo.webp')) ?>" alt="Logo Tirtanadi" class="h-full w-full object-contain"></div><div><p class="font-bold text-primary">PERUMDA TIRTANADI</p><p class="text-xs text-slate-500">Cabang Medan Denai</p></div></div></div>
        <p class="text-sm font-semibold uppercase tracking-wider text-primary">Selamat datang</p><h2 class="mt-2 text-3xl font-bold text-slate-900">Masuk ke sistem</h2><p class="mt-2 text-sm leading-6 text-slate-500">Gunakan akun yang telah diberikan administrator.</p>
        <form method="post" action="<?= e(url('/login')) ?>" class="mt-8 space-y-5" novalidate><?= csrf_field() ?>
            <div><label for="username" class="mb-2 block text-sm font-semibold text-slate-700">Username</label><input id="username" name="username" value="<?= e(old('username')) ?>" required autofocus autocomplete="username" class="form-input <?= error('username') ? 'form-input-error' : '' ?>" placeholder="Masukkan username"><p class="form-error"><?= e(error('username') ?? '') ?></p></div>
            <div><label for="password" class="mb-2 block text-sm font-semibold text-slate-700">Password</label><div class="relative"><input id="password" type="password" name="password" required autocomplete="current-password" class="form-input pr-12 <?= error('password') ? 'form-input-error' : '' ?>" placeholder="Masukkan password"><button type="button" class="password-toggle absolute inset-y-0 right-0 px-4 text-sm font-semibold text-primary" aria-label="Tampilkan password">Lihat</button></div><p class="form-error"><?= e(error('password') ?? '') ?></p></div>
            <button class="btn btn-primary flex w-full items-center justify-center py-3" type="submit">Masuk ke Sistem <span class="ml-2" aria-hidden="true">→</span></button>
        </form>
        <div class="auth-demo mt-8 rounded-lg border p-4 text-xs leading-5 text-slate-600"><p class="font-bold text-primary">Akun demo</p><p class="mt-1">Admin: <b>admin</b> / Admin123! &nbsp;·&nbsp; Pimpinan: <b>pimpinan</b> / Pimpinan123!</p></div>
    </div></section>
</main>
