server {
    listen 8080;
    listen [::]:8080;
    server_name localhost 127.0.0.1;

    root /home/shata/Documents/web-ta/public;
    index index.php;
    client_max_body_size 5m;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }

    location ~ /\. {
        deny all;
    }

    location ~* \.(?:env|sql|log|bak)$ {
        deny all;
    }
}
